name: deploy
on:
  workflow_run:
    workflows: ["build-push"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          script_stop: true
          script: |
            set -Eeuo pipefail
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            cd /srv/site
            docker compose pull
            docker compose up -d
            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
